# Dockerä¸Šã®ç’°å¢ƒç”¨

# è¡¨ç¤ºã•ã‚Œã‚‹é …ç›®ã®é †åºã®è¨­å®š(åŸºæœ¬ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã§è‰¯ã„)
format = """\
    ğŸ³ [ env ](bg:blue bold)[î‚°](blue) \
    $directory\
    $git_branch\
    $git_status\
    $line_break\
    $character\
"""

# ãƒ†ã‚­ã‚¹ãƒˆãŒå…¥åŠ›ã•ã‚Œã‚‹å ´æ‰€ã‚’ç¤ºã™æ–‡å­—ã®è¨­å®š
[character]
success_symbol = "[#](bold green)"
error_symbol = "[#](bold red)"

# æ™‚é–“ã®è¨­å®š
[time]
disabled = true # éè¡¨ç¤ºã«è¨­å®šã™ã‚‹ã¨ã€å¿…ãšä¸€è¡Œã«ãªã‚‹
